### ISSUE TITLE
General issues with the VM.

### ISSUE THREAD

**Issue by EternalV3** [Rerumu/Rerubi#10]
### Incorrect argument adjusting
Similar to #6, the stack is not handled correctly, causing weird bugs after things are supposed to be adjusted.
```lua
print((function () return nil end)(4))
```

### Environment handling
setfenv and getfenv are separated from the host environment.

### Lack of `LUA_COMPAT_VARARG` support
This isn't really an issue, but since it is part of the default Lua5.1 package it would make of a more complete experience

### Broken IEEE unpacking
Does not meet the full IEEE 754 standard.
```lua
print(-0)
```

### Forced `LUAI_MAXCCALLS`
The recursive limit is greatly shortened due to the wrapping of the entire VM in pcall.

### Pcall... Yielding?
```lua
function co()
  print(1)
  coroutine.yield()
  print(2)
end

local thread = coroutine.create(co)
coroutine.resume(thread)
coroutine.resume(thread)
```

### `OP_TFOORLOOP` issue
I really don't feel like digging around for what the problem is, but I was able to reproduce a working example.

***This no longer works for some reason.***

```lua
local function iter(lcnt)
  return function(x, y)
      return y - 1
  end, nil, nil
end

for x, y in iter(5) do end
```

### Incorrect jumping
I noticed some missing jumps, without going through the entire VM I can say I noticed it first in `OP_TESTSET`

**Comment by Rerumu** [comment]
Regarding the pcall yield issue, I was referring to things such as Roblox in which `wait()` inside a coroutine would have it desync with surrounding code, so it uses pcall instead of coroutines.

**Comment by Rerumu** [comment]
Most if not all these issues have been fixed. Reopen with any specific ones if I missed any.
