### ISSUE TITLE
Incorrect assumption of argument count.

### ISSUE THREAD

**Issue by EternalV3** [Rerumu/Rerubi#5]
Cause: [1](https://github.com/Rerumu/Rerubi/blob/master/Source.lua#L571) [2](https://github.com/Rerumu/Rerubi/blob/master/Source.lua#L618)

For both OP_TAIL/CALL the argument count is expected to be >= 1.

Example:
```lua
print((function(x) return x end)())
> (LUA_TNONE)
```

**Comment by Rerumu** [comment]
Issue fixed
