### ISSUE TITLE
Scoping error on reentry.

### ISSUE THREAD

**Issue by EternalV3** [Rerumu/Rerubi#7]
[Cause](https://github.com/Rerumu/Rerubi/blob/master/Source.lua#L1#L4)

'Quick-access' functions can go out of scope.

Example:
```lua
loadstring(string.dump(function() end))()
> attempt to call upvalue 'Select' (a nil value)
```

**Comment by Rerumu** [comment]
Don't really know what to do about this one; probably will revisit in the future.
