### ISSUE TITLE
Incorrect handling of OP_FORPREP.

### ISSUE THREAD

**Issue by EternalV3** [Rerumu/Rerubi#8]
[Cause](https://github.com/Rerumu/Rerubi/blob/master/Source.lua#L673-L678)

For init/limit/step value conversion is not handled, enforcement of only numbers is not present as well.

Example:
```lua
for i = 1, "2" do end
> attempt to compare number with string

for i = 1, {} do end
> attempt to compare number with table
```

**Comment by Rerumu** [comment]
Issue fixed and errors added
