### ISSUE TITLE
Incorrect handling of OP_CONCAT.

### ISSUE THREAD

**Issue by EternalV3** [Rerumu/Rerubi#9]
[Cause](https://github.com/Rerumu/Rerubi/blob/master/Source.lua#L468)

Concat does not attempt to convert any objects, along with this `table.concat` does not call the proper metamethod.

Example:
```lua
local x = {}
setmetatable(x, {__concat = function(x, y) return '__concat' end})
print(''..x)
> invalid value (table) at index 2 in table for 'concat'
```

**Comment by Rerumu** [comment]
Issue fixed
